#############################################################################################
#                                                                                           #
#                                    EXODUS PROJECT                                         #
#                                                                                           #
#                                     EXODUS HOMES                                          #
#                                  CONFIGURATION FILE                                       #
#                                                                                           #
#                                                                                           #
#############################################################################################

#Avaible Types: YAML or MySQL
#MySQL does not have support for importing homes from EssentialsX!
Database-Type: YAML
MySQL:
  host: localhost
  port: 3306
  database: exodus_homes
  username: root
  password:

#Prefix for messages
#Set '' if you don't want to use it!
Plugin-Prefix: '&8[&b&lHomes&8] '

#Worlds where homes are allowed!
Whitelist-Worlds:
  - world

#Words not allowed for names
#Check name in /homes create <name>
Blacklist-Names:
  - fuck
  - bitch

#Delay for teleport to home
#Set 0 for disable
Teleport-Delay:
  Time: 5 #in seconds

#Feature for fill inventory
#with items
#Set false for disable!
Background:
  Enable: true
  Icon: BLACK_STAINED_GLASS_PANE
  Name: ''

#Use sounds that are in the
#version of your server!
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
Sounds:
  Volume: 2
  Pitch: 1.5
  Create-Home: ENTITY_PLAYER_LEVELUP
  Renamed-Home: BLOCK_ANVIL_HIT
  Delete-Home: ENTITY_VILLAGER_YES
  Teleport-Home: ENTITY_ENDERMAN_TELEPORT
  Waiting-Teleport: UI_BUTTON_CLICK
  Open-GUI: BLOCK_CHEST_OPEN