#############################################################################################
#                                                                                           #
#                                    EXODUS PROJECT                                         #
#                                                                                           #
#                                     EXODUS HOMES                                          #
#                                  CONFIGURATION FILE                                       #
#                                                                                           #
#                                                                                           #
#############################################################################################

#Avaible Types: YAML or MySQL
#Recommended MySQL!
Database-Type: YAML
MySQL:
  host: localhost
  port: 3306
  database: exodus_homes
  username: root
  password:

#Sets the maximum number of households
#in a group. You need give the permission:
#homes.group.<group> - case sensitive
#For example homes.group.member
#You can change groups name
#and add more groups!
Groups:
  Member: 1
  MVP: 3
  GOD: 5

#Worlds where homes are allowed!
Whitelist-Worlds:
  - world

#Words not allowed for names
#Check name in /homes create <name>
Blacklist-Names:
  - fuck
  - bitch

#Delay for teleport to home
#Set 0 for disable
Teleport-Delay:
  Time: 5 #in seconds

#Feature for fill inventory
#with items
#Set false for disable!
Background:
  Enable: true
  Icon: BLACK_STAINED_GLASS_PANE
  Name: ''

Titles:
  Enable: true
  Fade-In: 20
  Stay: 15
  Fade-Out: 20

#Use sounds that are in the
#version of your server!
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
Sounds:
  Volume: 2
  Pitch: 1.5
  Create-Home: ENTITY_PLAYER_LEVELUP
  Delete-Home: ENTITY_VILLAGER_YES
  Teleport-Home: ENTITY_ENDERMAN_TELEPORT
  Open-GUI: BLOCK_CHEST_OPEN

#Use particles that are in the
#version of your server!
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
Particles:
  Create-Home: VILLAGER_HAPPY
  Teleport-Home: SPELL_WITCH