name: ExodusHomes
version: ${project.version}
main: com.reussy.ExodusHomes
api-version: 1.13
authors: [ reussy ]
description: Set your homes easily!
softdepend:
  - EssentialsX

commands:
  exodushomes:
    description: Main Command for ExodusHomes.
  home:
    description: Main Command for Players.
    aliases:
      - homes
      - homegui
