name: ExodusHomes
version: ${project.version}
main: com.reussy.ExodusHomes
api-version: 1.13
authors: [ reussy ]
description: Set your homes easily!
softdepend:
  - PlaceholderAPI
  - EssentialsX
loadbefore:
  - EssentialsX


commands:
  eh:
    description: Main Command for ExodusHomes.
    aliases:
      - ehomes
  ehm:
    description: Command for Manage Players and Homes
    aliases:
      - ehmanage
  home:
    description: Main Command for Players.
    aliases:
      - homes

permissions:
  homes.command.admin:
    description: Permission for administrator commands
    default: op

  homes.command.manage:
    description: Permission for manage commands
    default: op

  homes.command.player:
    description: Permission for player commands

  homes.limit.*:
    description: No limit for create homes!
