name: ExodusHomes
version: ${project.version}
main: com.reussy.ExodusHomes
api-version: 1.13
authors: [ reussy ]
description: Set your homes easily!
softdepend:
  - PlaceholderAPI

commands:
  exodushomes:
    description: Main Command for ExodusHomes.
    aliases:
      - eh
      - ehomes
  exodushomesmanage:
    description: Command for Manage Players and Homes
    aliases:
      - ehm
      - ehmanage
  home:
    description: Main Command for Players.
    aliases:
      - homes
      - homegui

permissions:
  homes.command.admin:
    description: Permission for administrator commands
    default: op

  homes.command.player:
    description: Permission for player commands
